### PR TITLE
Resolves load error on Windows for vmware transport

### LINKED ISSUE #693: Required dependencies for vmware transport not shipped.
# Version:

3.5.2 and also seen in 3.7.2

# Environment:

Running from a Windows 10 machine with workstation installed.

# Scenario:

Executing profiles that use the vmware transport.

# Steps to Reproduce:

Attempt to execute a profile with the vmware transport.

# Expected Result:

The profile will execute using the vmware transport.

# Actual Result:

The execution fails with an error that the vmware transport cannot load a dependency on the local.rb file which does not seem to be included in workstation or inspec installations in the right locations for the vmware transport.

The vmware transport is in the train-3.5.2 gem while local and the rest are in the train-core-3.5.2 gem. Maybe an issue with using require_relative for local instead of require?

Adding error info:

PS > inspec exec D:\inspec\Profiles\vmware-vsphere-vm-7.0-stig-baseline -t vmware:// --input vmName=******** --show-progress --reporter=cli                                                          

Traceback (most recent call last):
        16: from D:/inspec/bin/inspec:272:in `<main>'
        15: from D:/inspec/bin/inspec:272:in `load'
        14: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.37.30/bin/inspec:11:in `<top (required)>'
        13: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/base_cli.rb:35:in `start'
        12: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        11: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        10: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         9: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         8: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/cli.rb:282:in `exec'
         7: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/cli.rb:282:in `new'
         6: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/runner.rb:78:in `initialize'
         5: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/runner.rb:86:in `configure_transport'
         4: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/backend.rb:38:in `create'
         3: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.7.2/lib/train/transports/vmware.rb:16:in `connection'
         2: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.7.2/lib/train/transports/vmware.rb:16:in `new'
         1: from D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.7.2/lib/train/transports/vmware.rb:37:in `initialize'
D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.7.2/lib/train/transports/vmware.rb:37:in `require_relative': cannot
load such file -- D:/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.7.2/lib/train/transports/local (LoadError)

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Related Issue

Fixes #693 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/train/transports/vmware.rb [hunk 1]
```diff
@@ -34,7 +34,7 @@ def initialize(options)
         @powershell_binary = detect_powershell_binary
 
         if @powershell_binary == :powershell
-          require_relative "local"
```
Comment (tas50) [inline lib/train/transports/vmware.rb:37]: This should stay as require_relative which is higher performance

require_relative "transports/local"

Comment (Vasu1105) [reply lib/train/transports/vmware.rb:37]: @tas50 require_relative is not working here as it's unable to load the local.rb file from the train-core gem.
